# Generated by Django 5.2.7 on 2025-11-11 02:11
# MODIFICADO: Esta migración no crea tablas, solo las registra para Django
# Las tablas reales se crean con SQL puro en 0002_db_objects.py

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Migración vacía - todas las tablas se crean con SQL puro en 0002_db_objects
        # Esto permite que Django registre que la migración se aplicó sin crear tablas duplicadas
    ]
