# Generated by Django 5.2.7 on 2025-11-09 07:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('webmaga', '0004_add_grupo_id_to_evento_cambio_colaborador'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioFotoPerfil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('archivo_tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('archivo_tamanio', models.BigIntegerField(blank=True, null=True)),
                ('url_almacenamiento', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='foto_perfil', to='webmaga.usuario')),
            ],
            options={
                'verbose_name': 'Foto de Perfil',
                'verbose_name_plural': 'Fotos de Perfil',
                'db_table': 'usuario_fotos_perfil',
            },
        ),
    ]
