# Generated by Django 5.2.7 on 2025-11-11 10:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmaga', '0006_seed_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocambiocolaborador',
            name='comunidad',
            field=models.ForeignKey(blank=True, db_column='comunidad_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_eventos', to='webmaga.comunidad'),
        ),
        migrations.AddField(
            model_name='eventocambiocolaborador',
            name='grupo_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='eventocambiocolaborador',
            name='region',
            field=models.ForeignKey(blank=True, db_column='region_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_eventos', to='webmaga.region'),
        ),
    ]
