# Generated by Django 5.2.7 on 2025-11-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmaga', '0006_eventocambiocolaborador_comunidad_and_more'),
        ('webmaga', '0007_eventocambiocolaborador_comunidad_and_more'),
    ]

    operations = [
    ]
