# Generated by Django 5.2.7 on 2025-11-29 10:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmaga', '0009_add_comunidad_region_to_eventocambiocolaborador_safe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['-fecha'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='actividadarchivo',
            options={'verbose_name': 'Archivo de Actividad', 'verbose_name_plural': 'Archivos de Actividades'},
        ),
        migrations.AlterModelOptions(
            name='actividadbeneficiario',
            options={'verbose_name': 'Beneficiario de Actividad', 'verbose_name_plural': 'Beneficiarios de Actividades'},
        ),
        migrations.AlterModelOptions(
            name='actividadcambio',
            options={'ordering': ['-fecha_cambio'], 'verbose_name': 'Cambio de Actividad', 'verbose_name_plural': 'Cambios de Actividades'},
        ),
        migrations.AlterModelOptions(
            name='actividadpersonal',
            options={'verbose_name': 'Personal de Actividad', 'verbose_name_plural': 'Personal de Actividades'},
        ),
        migrations.AlterModelOptions(
            name='beneficiario',
            options={'verbose_name': 'Beneficiario', 'verbose_name_plural': 'Beneficiarios'},
        ),
        migrations.AlterModelOptions(
            name='beneficiariofamilia',
            options={'verbose_name': 'Beneficiario Familia', 'verbose_name_plural': 'Beneficiarios Familias'},
        ),
        migrations.AlterModelOptions(
            name='beneficiarioindividual',
            options={'verbose_name': 'Beneficiario Individual', 'verbose_name_plural': 'Beneficiarios Individuales'},
        ),
        migrations.AlterModelOptions(
            name='beneficiarioinstitucion',
            options={'verbose_name': 'Beneficiario Institución', 'verbose_name_plural': 'Beneficiarios Instituciones'},
        ),
        migrations.AlterModelOptions(
            name='bitacoratransaccion',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Bitácora de Transacción', 'verbose_name_plural': 'Bitácora de Transacciones'},
        ),
        migrations.AlterModelOptions(
            name='cambioevidencia',
            options={'verbose_name': 'Evidencia de Cambio', 'verbose_name_plural': 'Evidencias de Cambios'},
        ),
        migrations.AlterModelOptions(
            name='colaborador',
            options={'ordering': ['nombre'], 'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='colasincronizacion',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Registro de Cola de Sincronización', 'verbose_name_plural': 'Cola de Sincronización'},
        ),
        migrations.AlterModelOptions(
            name='comunidad',
            options={'ordering': ['region', 'nombre'], 'verbose_name': 'Comunidad', 'verbose_name_plural': 'Comunidades'},
        ),
        migrations.AlterModelOptions(
            name='comunidadarchivo',
            options={'verbose_name': 'Archivo de Comunidad', 'verbose_name_plural': 'Archivos de Comunidades'},
        ),
        migrations.AlterModelOptions(
            name='comunidadautoridad',
            options={'verbose_name': 'Autoridad de Comunidad', 'verbose_name_plural': 'Autoridades de Comunidades'},
        ),
        migrations.AlterModelOptions(
            name='comunidadgaleria',
            options={'verbose_name': 'Galería de Comunidad', 'verbose_name_plural': 'Galerías de Comunidades'},
        ),
        migrations.AlterModelOptions(
            name='conflictosincronizacion',
            options={'ordering': ['-detectado_en'], 'verbose_name': 'Conflicto de Sincronización', 'verbose_name_plural': 'Conflictos de Sincronización'},
        ),
        migrations.AlterModelOptions(
            name='dispositivoregistrado',
            options={'verbose_name': 'Dispositivo Registrado', 'verbose_name_plural': 'Dispositivos Registrados'},
        ),
        migrations.AlterModelOptions(
            name='eventocambiocolaborador',
            options={'ordering': ['-fecha_cambio'], 'verbose_name': 'Cambio de Evento por Colaborador', 'verbose_name_plural': 'Cambios de Evento por Colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='eventosevidenciascambios',
            options={'verbose_name': 'Evidencia de Cambio de Evento', 'verbose_name_plural': 'Evidencias de Cambios de Eventos'},
        ),
        migrations.AlterModelOptions(
            name='eventosgaleria',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Imagen de Galería', 'verbose_name_plural': 'Imágenes de Galería'},
        ),
        migrations.AlterModelOptions(
            name='evidencia',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Evidencia', 'verbose_name_plural': 'Evidencias'},
        ),
        migrations.AlterModelOptions(
            name='passwordresetcode',
            options={'verbose_name': 'Código de Recuperación', 'verbose_name_plural': 'Códigos de Recuperación'},
        ),
        migrations.AlterModelOptions(
            name='puesto',
            options={'ordering': ['nombre'], 'verbose_name': 'Puesto', 'verbose_name_plural': 'Puestos'},
        ),
        migrations.AlterModelOptions(
            name='recordatorio',
            options={'ordering': ['due_at'], 'verbose_name': 'Recordatorio', 'verbose_name_plural': 'Recordatorios'},
        ),
        migrations.AlterModelOptions(
            name='recordatoriocolaborador',
            options={'verbose_name': 'Colaborador del Recordatorio', 'verbose_name_plural': 'Colaboradores del Recordatorio'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['codigo'], 'verbose_name': 'Región', 'verbose_name_plural': 'Regiones'},
        ),
        migrations.AlterModelOptions(
            name='regionarchivo',
            options={'verbose_name': 'Archivo de Región', 'verbose_name_plural': 'Archivos de Regiones'},
        ),
        migrations.AlterModelOptions(
            name='regiongaleria',
            options={'verbose_name': 'Galería de Región', 'verbose_name_plural': 'Galerías de Regiones'},
        ),
        migrations.AlterModelOptions(
            name='sesionoffline',
            options={'verbose_name': 'Sesión Offline', 'verbose_name_plural': 'Sesiones Offline'},
        ),
        migrations.AlterModelOptions(
            name='tarjetadato',
            options={'verbose_name': 'Tarjeta de Datos', 'verbose_name_plural': 'Tarjetas de Datos'},
        ),
        migrations.AlterModelOptions(
            name='tipoactividad',
            options={'verbose_name': 'Tipo de Actividad', 'verbose_name_plural': 'Tipos de Actividad'},
        ),
        migrations.AlterModelOptions(
            name='tipobeneficiario',
            options={'verbose_name': 'Tipo de Beneficiario', 'verbose_name_plural': 'Tipos de Beneficiario'},
        ),
        migrations.AlterModelOptions(
            name='tipocomunidad',
            options={'verbose_name': 'Tipo de Comunidad', 'verbose_name_plural': 'Tipos de Comunidad'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['username'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='usuariofotoperfil',
            options={'verbose_name': 'Foto de Perfil', 'verbose_name_plural': 'Fotos de Perfil'},
        ),
        migrations.CreateModel(
            name='BeneficiarioAtributoTipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atributos_tipos_creados', to='webmaga.usuario')),
            ],
            options={
                'verbose_name': 'Tipo de Atributo de Beneficiario',
                'verbose_name_plural': 'Tipos de Atributos de Beneficiarios',
                'db_table': 'beneficiario_atributos_tipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='BeneficiarioFoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('archivo_tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('archivo_tamanio', models.BigIntegerField(blank=True, null=True)),
                ('url_almacenamiento', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('beneficiario_individual', models.OneToOneField(db_column='beneficiario_individual_id', on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='webmaga.beneficiarioindividual')),
            ],
            options={
                'verbose_name': 'Foto de Beneficiario',
                'verbose_name_plural': 'Fotos de Beneficiarios',
                'db_table': 'beneficiario_fotos',
            },
        ),
        migrations.CreateModel(
            name='BeneficiarioAtributo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('beneficiario_individual', models.ForeignKey(db_column='beneficiario_individual_id', on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='webmaga.beneficiarioindividual')),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atributos_creados', to='webmaga.usuario')),
                ('atributo_tipo', models.ForeignKey(db_column='atributo_tipo_id', on_delete=django.db.models.deletion.RESTRICT, related_name='valores', to='webmaga.beneficiarioatributotipo')),
            ],
            options={
                'verbose_name': 'Atributo de Beneficiario',
                'verbose_name_plural': 'Atributos de Beneficiarios',
                'db_table': 'beneficiario_atributos',
                'ordering': ['atributo_tipo__nombre', 'valor'],
                'unique_together': {('beneficiario_individual', 'atributo_tipo', 'valor')},
            },
        ),
    ]
