# Generated by Django 5.2.7 on 2025-12-01 10:00

from django.db import migrations, models


def add_fecha_reinscripcion_if_not_exists(apps, schema_editor):
    """Agrega la columna fecha_reinscripcion solo si no existe"""
    with schema_editor.connection.cursor() as cursor:
        # Verificar si la columna existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.columns 
                WHERE table_schema = 'public' 
                AND table_name = 'actividad_beneficiarios'
                AND column_name = 'fecha_reinscripcion'
            );
        """)
        
        columna_existe = cursor.fetchone()[0]
        
        # Agregar columna solo si no existe
        if not columna_existe:
            cursor.execute("""
                ALTER TABLE actividad_beneficiarios 
                ADD COLUMN fecha_reinscripcion TIMESTAMPTZ NULL;
            """)


def remove_fecha_reinscripcion(apps, schema_editor):
    """Elimina la columna fecha_reinscripcion si existe"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE actividad_beneficiarios 
            DROP COLUMN IF EXISTS fecha_reinscripcion;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('webmaga', '0010_alter_actividad_options_and_more'),
    ]

    operations = [
        # Usar RunPython para fecha_reinscripcion (idempotente)
        migrations.RunPython(
            add_fecha_reinscripcion_if_not_exists,
            remove_fecha_reinscripcion,
        ),
        migrations.AddField(
            model_name='beneficiarioindividual',
            name='apellido_casada',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarioindividual',
            name='comunidad_linguistica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarioindividual',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarioindividual',
            name='primer_nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarioindividual',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarioindividual',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarioindividual',
            name='tercer_nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiarioindividual',
            name='apellido',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiarioindividual',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
