# Generated by Django 5.2.7 on 2025-12-01 10:00

from django.db import migrations, models


def add_all_columns_if_not_exists(apps, schema_editor):
    """Agrega todas las columnas solo si no existen (idempotente)"""
    with schema_editor.connection.cursor() as cursor:
        # Verificar columnas existentes en actividad_beneficiarios
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_schema = 'public' 
            AND table_name = 'actividad_beneficiarios';
        """)
        columnas_actividad = {row[0] for row in cursor.fetchall()}
        
        # Verificar columnas existentes en beneficiarios_individuales
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_schema = 'public' 
            AND table_name = 'beneficiarios_individuales';
        """)
        columnas_beneficiarios = {row[0] for row in cursor.fetchall()}
        
        # Agregar fecha_reinscripcion si no existe
        if 'fecha_reinscripcion' not in columnas_actividad:
            cursor.execute("""
                ALTER TABLE actividad_beneficiarios 
                ADD COLUMN fecha_reinscripcion TIMESTAMPTZ NULL;
            """)
        
        # Agregar columnas de beneficiarios_individuales si no existen
        columnas_a_agregar = {
            'apellido_casada': 'VARCHAR(150)',
            'comunidad_linguistica': 'VARCHAR(100)',
            'primer_apellido': 'VARCHAR(150)',
            'primer_nombre': 'VARCHAR(150)',
            'segundo_apellido': 'VARCHAR(150)',
            'segundo_nombre': 'VARCHAR(150)',
            'tercer_nombre': 'VARCHAR(150)',
        }
        
        for columna, tipo in columnas_a_agregar.items():
            if columna not in columnas_beneficiarios:
                cursor.execute(f"""
                    ALTER TABLE beneficiarios_individuales 
                    ADD COLUMN {columna} {tipo} NULL;
                """)


def remove_all_columns(apps, schema_editor):
    """Elimina todas las columnas agregadas si existen"""
    with schema_editor.connection.cursor() as cursor:
        # Eliminar fecha_reinscripcion
        cursor.execute("""
            ALTER TABLE actividad_beneficiarios 
            DROP COLUMN IF EXISTS fecha_reinscripcion;
        """)
        
        # Eliminar columnas de beneficiarios_individuales
        columnas_a_eliminar = [
            'apellido_casada',
            'comunidad_linguistica',
            'primer_apellido',
            'primer_nombre',
            'segundo_apellido',
            'segundo_nombre',
            'tercer_nombre',
        ]
        
        for columna in columnas_a_eliminar:
            cursor.execute(f"""
                ALTER TABLE beneficiarios_individuales 
                DROP COLUMN IF EXISTS {columna};
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('webmaga', '0010_alter_actividad_options_and_more'),
    ]

    operations = [
        # Usar RunPython para todas las columnas (idempotente)
        migrations.RunPython(
            add_all_columns_if_not_exists,
            remove_all_columns,
        ),
        migrations.AlterField(
            model_name='beneficiarioindividual',
            name='apellido',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiarioindividual',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
