# Generated by Django 5.2.7 on 2025-12-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmaga', '0010_alter_actividad_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadbeneficiario',
            name='fecha_reinscripcion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el beneficiario fue reinscrito/actualizado en este proyecto', null=True),
        ),
        migrations.AddField(
            model_name='beneficiarioindividual',
            name='apellido_casada',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarioindividual',
            name='comunidad_linguistica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarioindividual',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarioindividual',
            name='primer_nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarioindividual',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarioindividual',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarioindividual',
            name='tercer_nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiarioindividual',
            name='apellido',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiarioindividual',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
